
version: "3.3"

services:
    django:
        build: .
        command: "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./:/code
            - static_volume:/app/static
            - media_volume:/app/media
        env_file:
            - .env
        ports:
            - "8000:8000"
volumes:
    static_volume:
    media_volume: