# Generated by Django 5.0 on 2023-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='lot',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего редактирования'),
        ),
    ]
