# Generated by Django 5.0 on 2023-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0002_lot_date_added_lot_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать ли объявление'),
        ),
    ]
