# Generated by Django 5.0 on 2023-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0003_lot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение объявления'),
        ),
    ]
